buyer_attrs: &buyer_attrs
  market_value: 市值
  t_minus_1_market_value: t - 1 市值
  t_minus_2_market_value: t - 2 市值
  net_profit: 当年净利润
  t_minus_1_net_profit: t - 1 净利润
  t_minus_2_net_profit: t - 2 净利润
  operating_income: 营业收入
  t_minus_1_operating_income: t - 1 营业收入
  t_minus_2_operating_income: t - 2 营业收入
buyer:
  code: 代码
  name: 名称
  owner: 控股人
  industry: 行业
  <<: *buyer_attrs
target_attrs: &target_attrs
  registered_capital: 注册资本
  big_stockholder_percent: 大股东持股比例
  net_assets: 净资产
  liabilities: 债务
  total_assets: 当前总资产
  t_minus_1_total_assets: t - 1 总资产
  t_minus_2_total_assets: t - 2 总资产
  t_minus_1_net_assets: t - 1 净资产
  t_minus_2_net_assets: t - 2 净资产
  t_minus_1_operating_income: t - 1 营业收入
  t_minus_2_operating_income: t - 2 营业收入
  t_minus_1_net_profit: t - 1 净利润
  net_profit: 当年净利润
target:
  name: 名称
  owner: 控股人
  create_date: 成立时间
  industry: 行业
  description: 业务描述
  address: 地址
  <<: *target_attrs
